[package]
name = "viz"
version = "0.1.0"
authors = ["Wesley Aptekar-Cassels <me@wesleyac.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
hpgl = { path = "../hpgl" }
structopt = "0.3.14"
